import { site } from "./site";

export type Department =
  | "Design"
  | "Engineering"
  | "Security"
  | "Data"
  | "Product"
  | "Growth"
  | "Operations"
  | "Leadership";

export type Level = "Mid" | "Senior" | "Staff" | "Lead" | "Executive";

export type Job = {
  slug: string;
  title: string;
  department: Department;
  level: Level;
  type: "Full-time" | "Contract";
  location: string;
  stack: string;
  summary: string;
  about: string;
  responsibilities: string[];
  requirements: string[];
  niceToHave: string[];
  salary: { min: number; max: number };
};

export const equityNote =
  "Token or equity on top of base, sized to the role. Details come in the offer, not in this posting.";

export function formatSalary(min: number, max: number) {
  const usd = (n: number) => `$${Math.round(n / 1000)}k`;
  return `${usd(min)} – ${usd(max)} USD (base)`;
}

const salaryBySlug: Record<string, { min: number; max: number }> = {
  "web3-designer": { min: 125000, max: 160000 },
  "product-designer-dapps": { min: 130000, max: 165000 },
  "senior-web3-designer": { min: 165000, max: 200000 },
  "brand-designer-web3": { min: 115000, max: 150000 },
  "motion-designer-web3": { min: 120000, max: 155000 },
  "design-lead": { min: 175000, max: 215000 },
  "head-of-design": { min: 210000, max: 270000 },
  "smart-contract-engineer": { min: 145000, max: 180000 },
  "blockchain-engineer-evm": { min: 145000, max: 180000 },
  "solana-rust-engineer": { min: 150000, max: 185000 },
  "fullstack-web3-engineer": { min: 145000, max: 180000 },
  "frontend-dapp-engineer": { min: 140000, max: 175000 },
  "defi-protocol-engineer": { min: 185000, max: 225000 },
  "rwa-real-estate-engineer": { min: 145000, max: 180000 },
  "mobile-web3-engineer": { min: 140000, max: 175000 },
  "senior-smart-contract-engineer": { min: 180000, max: 220000 },
  "senior-blockchain-developer": { min: 180000, max: 220000 },
  "senior-fullstack-web3-engineer": { min: 180000, max: 220000 },
  "staff-principal-engineer": { min: 220000, max: 270000 },
  "blockchain-devops-engineer": { min: 140000, max: 175000 },
  "qa-engineer-web3": { min: 120000, max: 155000 },
  "engineering-manager": { min: 190000, max: 240000 },
  "director-of-engineering": { min: 220000, max: 280000 },
  "vp-of-engineering": { min: 250000, max: 320000 },
  "smart-contract-security-engineer": { min: 190000, max: 235000 },
  "head-of-security": { min: 220000, max: 290000 },
  "web3-data-engineer": { min: 145000, max: 180000 },
  "product-manager-web3": { min: 140000, max: 175000 },
  "senior-product-manager-web3": { min: 170000, max: 210000 },
  "tokenomics-researcher": { min: 160000, max: 200000 },
  "head-of-product": { min: 210000, max: 280000 },
  "web3-community-manager": { min: 90000, max: 120000 },
  "web3-developer-relations": { min: 140000, max: 175000 },
  "business-development-web3": { min: 130000, max: 170000 },
  "technical-writer-web3": { min: 105000, max: 140000 },
  "growth-marketing-web3": { min: 120000, max: 155000 },
  "head-of-growth": { min: 180000, max: 240000 },
  "web3-recruiter": { min: 110000, max: 145000 },
  "web3-delivery-lead": { min: 130000, max: 165000 },
  "legal-compliance-web3": { min: 180000, max: 230000 },
  "token-operations-finance": { min: 120000, max: 155000 },
  cto: { min: 280000, max: 360000 },
};

function role(
  slug: string,
  title: string,
  department: Department,
  level: Level,
  stack: string,
  summary: string,
  about: string,
  responsibilities: string[],
  requirements: string[],
  niceToHave: string[],
  type: Job["type"] = "Full-time",
): Job {
  const salary = salaryBySlug[slug];
  if (!salary) throw new Error(`Missing salary for ${slug}`);
  return {
    slug,
    title,
    department,
    level,
    type,
    location: "Remote",
    stack,
    summary,
    about,
    responsibilities,
    requirements,
    niceToHave,
    salary,
  };
}

export const jobs: Job[] = [
  role(
    "web3-designer",
    "Web3 Designer",
    "Design",
    "Mid",
    "Figma · dApps · brand",
    "The core design seat across Lootrushs, BrickFi, and client launches — product UI, wallet flows, and the visual system they share.",
    "Lootrushs is a remote Web3 studio. We design and ship BrickFi (fractional real-estate ownership, distributions, investor reporting) and client protocols with the dApps that sit on them. This role is not a marketing-only seat and not a brand-only seat. You will spend most weeks in product: invest, mint, swap, admin, and the failure states those flows always have.\n\nYou work daily with a frontend engineer and a PM or the CTO on smaller jobs. First month is BrickFi’s invest and position screens plus the lootrushs.com system so it stays consistent with the product. We overlap a few hours with US Eastern. Apply on this site with a resume and a portfolio link.",
    [
      "Own end-to-end dApp and marketing surfaces for BrickFi and assigned client work.",
      "Design wallet-connected flows including connect, wrong network, pending, revert, and success.",
      "Keep visual identity consistent across product UI, lootrushs.com, and launch pages.",
      "Hand Figma files engineers can implement without a walkthrough for every frame.",
      "Sit in engineering standups for the project you are staffed on.",
      "Do short usability sessions with people who have used a wallet, not only founders.",
      "Produce hiring and launch assets when a ship date needs them; product work still comes first.",
      "Document patterns (buttons, toasts, receipts) so the next project does not start from zero.",
    ],
    [
      "2–4 years product or visual design with shipped web work you can walk through.",
      "A portfolio that includes complex product UI — multi-step flows, not only landing pages.",
      "Comfortable in Figma, including components and variants another designer can inherit.",
      "You can write a short flow spec so an engineer can build without you on the call.",
      "Remote work with overlap on US Eastern mornings or afternoons.",
    ],
    [
      "A live crypto or fintech product in the portfolio",
      "Brand systems you maintained after launch",
      "Light prototyping in code",
      "Motion or prototype tools (Rive, Principle, ProtoPie)",
    ],
  ),
  role(
    "product-designer-dapps",
    "Product Designer, dApps",
    "Design",
    "Mid",
    "Figma · wallet UX · systems",
    "Specialize in wallet-connected product design for BrickFi and client dApps — invest, mint, swap, and admin, including the ugly middle of each flow.",
    "This seat is product-only. You will not be the person making conference booth graphics. You own BrickFi’s investor experience and the client dApp flows we staff you on: research, IA, UI, and the states that appear when a transaction fails.\n\nWe expect you to argue with engineering about what belongs on-chain versus in the UI. We expect you to sit with someone who has used MetaMask or Phantom and watch them get stuck. First quarter is BrickFi invest/position plus one client mint or vault UI. You report to the senior designer (or the CTO until that seat is filled).",
    [
      "Design BrickFi investor flows: property browse, share purchase, yield, statements, and support.",
      "Design client mint, swap, vault, and admin flows with pending, failed, and wrong-network states.",
      "Build and maintain a Figma library frontend actually uses (tokens, components, receipts).",
      "Prototype the risky interactions (connect, switch chain, paymaster) before they hit a sprint.",
      "Run lightweight usability tests and write up what you change because of them.",
      "Partner with the frontend engineer on edge cases: RPC lag, indexer delay, partial fills.",
      "Join client kickoffs when the engagement is a product surface.",
      "Keep accessibility basics (contrast, focus, copy length) in the files, not as a later pass.",
    ],
    [
      "3+ years product design on shipped web or mobile apps.",
      "A portfolio of multi-step, high-trust flows (wallet, payments, brokerage, identity, or similar).",
      "At least one product you owned after launch — not only a concept file.",
      "You can explain a flow in writing without a live Figma share.",
    ],
    ["Shipped Web3 UI", "Design-system ownership", "Motion for product (not only films)", "Research practice"],
  ),
  role(
    "senior-web3-designer",
    "Senior Web3 Designer",
    "Design",
    "Senior",
    "Product · brand · systems",
    "Set the quality bar for every screen we ship. Mentor mid designers. Partner with PMs and the CTO on what we refuse to design.",
    "You have designed crypto or complex fintech products before and can defend a simpler flow in a room with a founder. You still draw the hard screens. You also review mid-designer work before it hits engineering.\n\nYou report to Head of Design when that seat is filled, otherwise to the CTO. BrickFi’s investor dashboard and client wallet UX patterns are the current load. You will be in client workshops. You will not be asked to run the whole design org — that is Design Lead / Head of Design.",
    [
      "Lead design on BrickFi and other flagship surfaces: investor, admin, and reporting.",
      "Define reusable wallet UX patterns (connect, switch chain, paymaster, receipt) across clients.",
      "Mentor mid designers: critiques, hiring input, and pairing on files.",
      "Present work to clients and to studio leadership without a deck of filler slides.",
      "Cut scope when a brief asks for a marketplace, a token, and a mobile app in one sprint.",
      "Hold the line on empty, error, and admin states — a flow is not done at the happy path.",
      "Partner with frontend on implementation QA for the flows you designed.",
      "Contribute to lootrushs.com and launch pages when they need product-quality craft.",
    ],
    [
      "5+ years product design, including senior ownership of a live product.",
      "Shipped Web3 or adjacent high-trust products (payments, brokerage, identity, trading).",
      "Evidence you have mentored another designer or been the sole designer on an engineering team.",
      "You can run a workshop and leave with decisions, not a mural of sticky notes.",
    ],
    ["Design leadership without people-management title", "RWA or real-estate products", "Writing design RFCs", "Facilitation training"],
  ),
  role(
    "brand-designer-web3",
    "Brand Designer, Web3",
    "Design",
    "Mid",
    "Identity · launch · campaigns",
    "Give Lootrushs and client protocols a visual system that holds up on launch day, in product chrome, and on a docs site.",
    "We already have a gold-and-dark studio language. This seat extends it and builds client identities that do not look like every other dark-mode crypto site. You will own identity, type, color, launch kits, and the look of lootrushs.com in partnership with product design.\n\nYou are not the only designer — product designers own dApp flows. You join when a new protocol needs a mark, a launch film still, a careers campaign, or when the product UI is drifting from the brand. Contractors may help on volume; you own the system.",
    [
      "Create and evolve brand systems for the studio and for named client protocols.",
      "Design launch, hiring, and campaign assets that match the product, not a separate “crypto aesthetic.”",
      "Partner with product designers so in-product chrome (empty states, receipts) uses the same language.",
      "Produce tight files for web, social, and print when we do events.",
      "Maintain the Lootrushs and BrickFi visual kits so engineers and writers can pull from them.",
      "Art-direct photos and motion briefs so we do not ship mismatched stock.",
      "Review vendor or contractor work against the system.",
    ],
    [
      "A strong identity portfolio: marks, type, color, and how they landed in a real product or site.",
      "Experience shipping brand into a live website or app, not only a PDF guidelines book.",
      "You can take verbal feedback from a founder and return options with a recommendation.",
    ],
    ["Crypto or culture work you are proud of", "3D", "Motion", "Art direction of photography"],
  ),
  role(
    "motion-designer-web3",
    "Motion / 3D Designer, Web3",
    "Design",
    "Mid",
    "After Effects · Rive · 3D",
    "Make product and launch motion that still loads — BrickFi, client reveals, and in-app delight without wrecking performance.",
    "This is a contract seat because our motion load spikes around launches. You will animate product (toasts, receipts, empty states) and brand (launch films, careers, BrickFi property stories). Web3 marketing that is only static cards dies in the feed; motion that is 12MB also dies.\n\nYou work with the brand designer and a product designer. Engineers need Lottie/Rive or equivalent, not a 4K ProRes they cannot ship. Typical engagement is 3–6 months with a chance to extend around BrickFi and client drops.",
    [
      "Design motion for dApps, launches, and hiring campaigns with a performance budget.",
      "Build Lottie, Rive, or equivalent files frontend can implement.",
      "Collaborate on 3D or hero treatments for BrickFi properties and studio films.",
      "Hand off specs (timing, easing, reduced-motion fallback) engineers can follow.",
      "Storyboard launch sequences before you animate the whole thing.",
      "Stay inside brand type and color; we do not need a second identity in After Effects.",
    ],
    [
      "A motion reel. Tools are flexible; taste and shipping constraints are not.",
      "At least one example of motion that shipped inside a product, not only a film.",
      "You can take a Figma file and return an implementable animation, not only a concept.",
    ],
    ["Rive", "Spline or Three.js", "Game VFX", "Previous crypto or fintech motion"],
    "Contract",
  ),
  role(
    "design-lead",
    "Design Lead",
    "Design",
    "Lead",
    "Team · product · clients",
    "Run design day to day — staffing, critiques, and the quality of every client surface — while still designing the hardest work.",
    "You still design, but you also make the team faster. Head of Design (or the CTO) sets the bar; you staff projects, run critiques, and are the senior designer in the room with clients.\n\nThe bench today is mid and senior ICs plus a brand/motion mix. You will hire the next mid-to-senior designers. You will not own executive brand strategy or the company P&L. You will own whether BrickFi and client UIs look like one studio.",
    [
      "Lead critiques and design staffing across BrickFi and client projects.",
      "Own hiring loops for mid through senior designers with the recruiter or CTO.",
      "Set process with product and engineering: when files are ready, how reviews work.",
      "Be the senior designer in client workshops and mid-project reviews.",
      "Still take a flagship flow yourself when the team is short.",
      "Protect focus: kill drive-by requests that are not on the ship list.",
      "Coach ICs on writing and presenting, not only pixels.",
    ],
    [
      "You have led designers on shipped products (title can be lead, manager, or founding designer).",
      "Web3 or fintech craft plus the ability to give hard feedback without theatre.",
      "Evidence you have hired or closed at least one designer.",
      "You can still open Figma and finish a flow.",
    ],
    ["Studio or agency lead experience", "Head-of-one at a startup", "Multi-timezone teams"],
  ),
  role(
    "head-of-design",
    "Head of Design",
    "Design",
    "Executive",
    "Org · craft · brand",
    "Own design at Lootrushs — product, brand, and the standard we sell to clients — from IC through lead.",
    "This is the top of the design ladder. You sit with the CTO and Head of Product. You still have taste; you also have an org: hiring, levels, rituals, and when we say no to a client’s “just make it look like [competitor].”\n\nBrickFi and the studio brand are yours to protect. You will hire a Design Lead if you do not want to run day-to-day staffing yourself. You will still review the riskiest surfaces before they ship.",
    [
      "Set design strategy for the studio and BrickFi.",
      "Build the design org: hiring, levels, critiques, and pairing with engineering.",
      "Guard brand and product quality at executive level, including client escalations.",
      "Represent design in client and leadership conversations.",
      "Own the quality of lootrushs.com and careers as part of the product, not a side project.",
      "Decide when we use contractors versus full-time.",
      "Hold a personal craft bar — you can still redesign a flow if the team is stuck.",
    ],
    [
      "Led a design org, or were the founding designer who scaled one past yourself.",
      "Shipped Web3 or other complex, high-trust product orgs.",
      "You have hired and leveled designers, not only directed vendors.",
      "Comfortable in a studio that does both a owned product (BrickFi) and client work.",
    ],
    ["Public craft", "Multi-brand systems", "Executive communication with non-designers"],
  ),
  role(
    "smart-contract-engineer",
    "Smart Contract Engineer",
    "Engineering",
    "Mid",
    "Solidity · Foundry",
    "Implement and test production Solidity — tokens, vaults, staking, and BrickFi issuance — with Foundry, not tutorial repos.",
    "You join a protocol pod with a senior contract engineer and whoever owns the dApp. Typical work is a specified module: access control, events, tests, a deploy script, and an ABI frontend can use.\n\nWe use Foundry. PRs that merge without tests or without a note on upgrade and admin powers get bounced. You do not need to have led an audit. You do need a public network you have shipped to. First projects are likely a BrickFi module or a client vault/staking piece.",
    [
      "Implement contract modules for BrickFi (share token, distribution, allowlists) and client protocols.",
      "Write Foundry unit, fork, and invariant tests for the code you own.",
      "Document admin roles, pause paths, and what happens if a keeper misses a window.",
      "Gas-review your own diffs before asking for a senior look.",
      "Help frontend with ABIs, events, and expected revert reasons.",
      "Join testnet and mainnet deploys for the modules you wrote.",
      "Read OpenZeppelin and our internal patterns before inventing a new access-control story.",
      "Leave a changelog and a threat note on every module that can move funds.",
    ],
    [
      "2+ years professional software, including Solidity in production. A public explorer link helps.",
      "Daily fluency with Foundry or Hardhat: tests, forks, scripting.",
      "You can explain how you would upgrade, pause, or migrate a live contract.",
      "Clear written English for PRs and client notes.",
    ],
    ["An audit you participated in", "ERC-4626, 3643, or 1155 in production", "TypeScript deploy scripts"],
  ),
  role(
    "blockchain-engineer-evm",
    "Blockchain Engineer, EVM",
    "Engineering",
    "Mid",
    "Ethereum · L2s · ethers",
    "Build across the EVM stack — contracts, scripts, indexers, and the glue that keeps L2 products live on Ethereum, Polygon, Arbitrum, Base, Optimism, and BNB Chain.",
    "This is not a Solidity-only job and not a frontend job. You own integrations: deploy scripts, chain adapters, nonce and RPC failure, L2 quirks, and the monitoring that tells us a keeper died.\n\nLootrushs ships on several EVM networks. You should already know how those environments differ (finality, gas, bridges, explorers). You will pair with a contract engineer on modules and with Ops on RPCs. BrickFi currently sits on Ethereum and Polygon; client work shows up on Base and Arbitrum often.",
    [
      "Implement integrations, deploy scripts, and chain adapters for the networks we staff.",
      "Debug reorgs, nonce issues, RPC failures, and L2-specific surprises.",
      "Stand up monitoring for transactions, events, and keepers.",
      "Support multi-network client launches (config, addresses, explorers, faucet notes).",
      "Write runbooks for the next person who has to redeploy at 11pm.",
      "Help frontend with chain IDs, addresses, and expected confirmation behavior.",
      "Keep staging and prod configs from drifting without a PR.",
    ],
    [
      "2+ years of EVM production work — not only a hackathon.",
      "Solidity plus TypeScript or Python tooling you have shipped.",
      "You have operated or closely supported at least one live network integration.",
    ],
    ["Account abstraction", "OP Stack or Orbit", "The Graph or a custom indexer", "On-call experience"],
  ),
  role(
    "solana-rust-engineer",
    "Solana / Rust Engineer",
    "Engineering",
    "Mid",
    "Rust · Anchor · Solana",
    "Write Solana programs and the off-chain services around them for games, markets, and consumer dApps.",
    "Most of our volume is EVM. We still take Solana work — compressed NFTs, in-game economies, consumer mints — and need someone who has shipped a program, not only completed a bootcamp.\n\nYou own program design, Anchor tests, and the TypeScript clients that talk to them. You will not be asked to also own the Solidity queue. You will be asked to estimate compute, accounts, and client UX honestly before we sign a date.",
    [
      "Design and ship Anchor or native programs for the project you are staffed on.",
      "Handle accounts, PDAs, compute limits, and compressed NFTs without kicking them to later.",
      "Write robust TypeScript clients and transaction builders frontend can call.",
      "Load-test before mainnet; write a rollback note if we need one.",
      "Document upgrade authority, freeze, and how ops should run the program.",
      "Pair with a frontend engineer on wallet adapters and error mapping.",
      "Estimate compute and rent in writing during scoping.",
    ],
    [
      "Production Rust.",
      "At least one Solana program on mainnet or a serious devnet that other people used.",
      "TypeScript clients you are willing to put in the application.",
    ],
    ["Compressed NFTs", "Jito / priority fees", "Move", "Game or NFT marketplace work"],
  ),
  role(
    "fullstack-web3-engineer",
    "Full-stack Web3 Engineer",
    "Engineering",
    "Mid",
    "Next.js · Solidity · wagmi",
    "Ship the whole slice: contracts or integrations, a small API or indexer consumer, and wallet-connected UI for client dApps and BrickFi.",
    "A lot of our engagements are too small for a dedicated protocol person and a dedicated frontend person the entire time. This seat is for someone who can move from a Solidity interface to a Next.js screen in the same week.\n\nBrickFi reporting (on-chain position to a document the investor can download) is a current example of that slice. You will talk to clients on implementation details once scope is set — you will not be asked to sell.",
    [
      "Build dApps with Next.js, wagmi/viem, and connectors.",
      "Implement or integrate contracts and subgraphs or a TypeScript indexer.",
      "Own auth, session, and wallet error states for the features you ship.",
      "Write TypeScript server routes when a flow should not live only in the browser.",
      "Add tests for the part you own (Foundry and/or frontend).",
      "Hand off runbooks: env vars, admin txs, what to do if the indexer lags.",
      "Work directly with the designer and PM on the same ticket, not a weekly dump.",
    ],
    [
      "3+ years full-stack including at least one production Web3 app.",
      "Strong TypeScript.",
      "Enough Solidity (or equivalent) to own a module or a serious integration.",
    ],
    ["The Graph, Ponder, or Envio", "Paymasters", "Mobile", "Postgres"],
  ),
  role(
    "frontend-dapp-engineer",
    "Frontend dApp Engineer",
    "Engineering",
    "Mid",
    "React · wagmi · viem",
    "Make wallet-connected products feel like real software — mint, swap, invest, and admin that do not stall at Connect.",
    "You own connectors, transaction states, chain switching, and the details that make a dApp usable. TypeScript, Next.js, wagmi/viem. We do not need another landing page.\n\nYou work with one product designer and whoever owns the contracts. Code lives in GitHub; reviews are expected the same day when we are close to a launch. BrickFi’s dashboard and a client mint/admin are the usual starting work.",
    [
      "Build responsive dApp UIs in React / Next.js from Figma with real chain state.",
      "Handle connect, signatures, gas, receipts, and recovery — including failed and stuck txs.",
      "Translate protocol state into clear screens when the indexer is behind.",
      "Raise accessibility and performance; we pay for the RPC calls users trigger.",
      "Add coverage for flows that lose money if they break (invest, withdraw, admin pause).",
      "Fix production bugs with a tx hash in the ticket.",
      "Share a small library of wallet components across BrickFi and clients when patterns stabilize.",
    ],
    [
      "3+ years production React.",
      "Shipped at least one wallet-connected product.",
      "Comfortable with Next.js App Router and TypeScript.",
      "You can debug a failed transaction in a block explorer without waiting for the contract author.",
    ],
    ["SIWE / passkeys", "Design systems", "Motion implementation", "Account abstraction UI"],
  ),
  role(
    "defi-protocol-engineer",
    "DeFi Protocol Engineer",
    "Engineering",
    "Senior",
    "AMMs · lending · vaults",
    "Design and implement DeFi primitives: markets, liquidity, yield, and risk — not wrap a fork and call it a protocol.",
    "You understand how AMMs, lending, and vaults fail in the wild: oracle manipulation, leftover approvals, broken invariants, keeper gaps. Clients hire us to survive that, not to redeploy a tutorial vault.\n\nYou will specify modules, write economic and invariant tests, and document operator runbooks. You work with a security engineer on launch gates. Senior bar: you have shipped or materially contributed to a live protocol other people used with money.",
    [
      "Specify and implement DeFi modules with explicit risk (oracles, liquidations, fees).",
      "Write economic and invariant tests, not only happy-path unit tests.",
      "Review oracle, keeper, and bridge integrations before they are “done.”",
      "Document operator runbooks: who can pause, who can set fees, what happens on a stale oracle.",
      "Estimate and sequence work so an audit can happen before mainnet.",
      "Explain tradeoffs to a PM and a non-technical founder without hiding the danger.",
      "Mentor mid contract engineers on this class of bugs.",
    ],
    [
      "Shipped or materially contributed to a live DeFi protocol.",
      "Deep Solidity and testing (Foundry fuzz/invariants or equivalent).",
      "You can talk through a historical exploit and what you would have changed in the design.",
    ],
    ["Quant or research background", "Restaking", "Keeper networks", "Published postmortems"],
  ),
  role(
    "rwa-real-estate-engineer",
    "RWA / Real Estate Engineer",
    "Engineering",
    "Mid",
    "Tokenization · BrickFi · Solidity",
    "Build on-chain real estate and RWA products — fractional shares, distributions, eligibility, and investor reporting on BrickFi.",
    "BrickFi is our real estate investment platform. You extend tokenization, issuance, and the investor dashboard. Legal and eligibility rules are part of the job. We will not ask you to invent securities advice; you will implement the gates counsel specifies.\n\nThis can be your primary product (not leftover hours from a DEX). You work with the BrickFi PM and designer. Transfers, lockups, and reporting have to match what we told the investor — tests and an audit trail are not optional.",
    [
      "Implement share issuance, transfers, lockups, and distributions.",
      "Connect on-chain state to investor and admin UIs.",
      "Work with product on KYC and eligibility gates; do not collect extra PII on a whim.",
      "Harden reporting and audit trails for anything that moves money or shares.",
      "Write tests that cover failed eligibility, paused issuance, and distribution edge cases.",
      "Triage production issues with tx hashes and indexer lag in mind.",
      "Document admin powers so ops and counsel can review them.",
    ],
    [
      "Production Solidity or full-stack Web3, with at least one live app.",
      "Interest in RWA or fintech and patience for product constraints (eligibility, reporting).",
      "TypeScript strong enough to own or pair on the dashboard.",
    ],
    ["ERC-3643 / 1400 or similar permissioned tokens", "KYC providers", "Real estate or proptech domain"],
  ),
  role(
    "mobile-web3-engineer",
    "Mobile Web3 Engineer",
    "Engineering",
    "Mid",
    "React Native · WalletConnect",
    "Ship iOS and Android experiences that talk to wallets and Lootrushs products without a desktop crutch.",
    "Consumer crypto still happens on phones. BrickFi and some client work need invest and account flows that work in a pocket: WalletConnect, deep links, backgrounding, and chain switch.\n\nYou will own mobile dApp paths. You will not be asked to rewrite our entire web stack in React Native on week one. We currently lean React Native / Expo; native Swift or Kotlin is a plus when WalletConnect is not enough.",
    [
      "Build React Native or native screens for invest and account flows.",
      "Integrate WalletConnect, deep links, and push where we actually need them.",
      "Handle background, session expiry, and chain switch on mobile.",
      "Partner with design on thumb-first UX; desktop Figma is not a spec.",
      "Share types and ABIs with the web team so we do not drift.",
      "Test on real devices and at least one popular mobile wallet.",
      "Document store-release and deep-link setup for Ops.",
    ],
    [
      "Shipped a production mobile app (App Store or Play).",
      "Comfort with wallet or payments SDKs.",
      "TypeScript or a native language you can ship in.",
    ],
    ["Expo", "Account-abstraction wallets", "Swift or Kotlin", "Prior crypto mobile work"],
  ),
  role(
    "senior-smart-contract-engineer",
    "Senior Smart Contract Engineer",
    "Engineering",
    "Senior",
    "Solidity · Foundry · OpenZeppelin",
    "Own protocol-grade Solidity for tokens, vaults, staking, and custom logic — including BrickFi and client launches.",
    "Senior seat: you set patterns, review PRs, and stay through deploy. You will be in audit calls. You will tell a client no when they want an owner that can rug.\n\nCurrent load is BrickFi issuance and client vault/staking work. You work with a mid contract engineer, security, and frontend. Compensation is $180k–$220k base plus token or equity in the offer.",
    [
      "Write, test, and ship Solidity with Foundry or Hardhat.",
      "Model access control, upgrades, pauses, and invariants before the first line of happy-path code.",
      "Gas-optimize hot paths without hiding complexity.",
      "Lead reviews and raise the engineering bar for mid ICs.",
      "Specify threat models: admin keys, oracles, reentrancy, upgrade mistakes.",
      "Run or coordinate fuzzing on the riskiest paths.",
      "Estimate chain work honestly in client scoping calls.",
      "Pair with Ops on deploy keys, dry runs, and mainnet.",
    ],
    [
      "4+ years shipping production Solidity.",
      "Fuzzing and fork-testing as a habit, not a slide.",
      "You have taken work through an external audit or a serious internal review.",
      "You can read TypeScript well enough to catch ABI and indexing mistakes.",
    ],
    ["Audit experience", "Formal verification", "Move or Vyper", "L2 production"],
  ),
  role(
    "senior-blockchain-developer",
    "Senior Blockchain Developer",
    "Engineering",
    "Senior",
    "Solidity · EVM · TypeScript",
    "Own production blockchain work end to end — contracts, integrations, and the systems around them — on BrickFi and client platforms.",
    "This is the senior IC bar for chain engineering at Lootrushs. We staff it when a client needs one person who can hold the whole chain slice: design, implementation, review, deploy order, and what waits for an audit.\n\nYou still write code. You also split work for a mid engineer. Base is $180k–$220k USD, plus token or equity in the offer. Remote, overlap with US Eastern.",
    [
      "Design, implement, and ship smart contracts and chain integrations.",
      "Lead reviews, testing, and mainnet deploys across EVM networks we support.",
      "Partner with product, design, and frontend on wallet and protocol UX.",
      "Raise the bar for mid-level engineers and launch quality.",
      "Coordinate testnet → audit → mainnet with Ops (keys, multisig, monitoring).",
      "Join scoping calls and say what will not fit the date.",
      "Write the architecture note another engineer can follow six months later.",
    ],
    [
      "4+ years shipping production blockchain software.",
      "Deep Solidity/EVM (or equivalent chain depth) plus strong TypeScript.",
      "You have taken protocol or product work through audit and mainnet.",
    ],
    ["Foundry", "L2s", "RWA / BrickFi-style products", "Incident response"],
  ),
  role(
    "senior-fullstack-web3-engineer",
    "Senior Full-stack Web3 Engineer",
    "Engineering",
    "Senior",
    "Protocol · product · delivery",
    "Lead full-stack delivery on client builds: architecture, unblocking, and the last mile to mainnet.",
    "You can still write the feature. You also split the work so a mixed team ships. This is the person we put on a client when the work is a protocol plus a dApp and we need one technical owner who talks to the client without overselling.\n\nYou unblock mid and senior engineers, own production incidents with DevOps, and keep the architecture from growing a second indexer “just in case.”",
    [
      "Architect dApp and contract slices for a project and write them down.",
      "Unblock mid and senior engineers; take the gnarly integration yourself when needed.",
      "Own production incidents with DevOps until the runbook exists.",
      "Talk to clients about implementation without promising dates engineering has not signed.",
      "Review both Solidity and TypeScript PRs for the project you lead.",
      "Sequence deploy: what can go to testnet, what waits for audit, what is UI-only.",
      "Leave the next engineer a README that is not a lie.",
    ],
    [
      "5+ years full-stack, 2+ in Web3 production.",
      "Evidence you have led a launch (title can be senior, lead, or staff IC).",
      "You can review a contract PR and a React PR in the same afternoon.",
    ],
    ["Tech lead experience", "RWA", "Solana and EVM", "Client-facing studio work"],
  ),
  role(
    "staff-principal-engineer",
    "Staff / Principal Engineer",
    "Engineering",
    "Staff",
    "Architecture · multi-chain",
    "Set technical direction across protocols, BrickFi, and client stacks. Highest individual-contributor rung before management.",
    "You operate at company scope: standards, threat models, and the hard calls between chains. You still merge code. You are not a people manager; hiring stays with the CTO and engineering managers.\n\nYou write design docs. You review the riskiest diffs — BrickFi architecture, a client bridge, a wallet kit. You kill accidental complexity (new chains, new tokens, new dashboards) that does not serve a date.",
    [
      "Define architecture for multi-product, multi-chain work and socialize it in writing.",
      "Review the riskiest contract and infra changes before mainnet.",
      "Mentor seniors; you are not their manager.",
      "Represent engineering with the CTO in the hardest client technical conversations.",
      "Kill complexity that does not serve launch.",
      "Set defaults: upgrade patterns, review bar, which networks we take.",
      "Lead incident reviews when a production protocol misbehaves.",
    ],
    [
      "Staff or principal scope in production systems, including real blockchain work (not only a side NFT).",
      "A paper trail: RFCs, postmortems, or protocols other engineers follow.",
      "You can still implement a feature if the team is short.",
    ],
    ["Published protocols", "Incident command", "Formal methods", "Multi-chain production"],
  ),
  role(
    "blockchain-devops-engineer",
    "Blockchain DevOps Engineer",
    "Engineering",
    "Mid",
    "RPCs · Kubernetes · CI",
    "Keep nodes, indexers, relayers, and deploys healthy when the chain gets noisy.",
    "You own merge-to-mainnet: CI, deploy keys, RPC strategy, and on-call dashboards. We are a studio, not a 24/7 trading firm, but we have keepers, relayers, and client mainnets.\n\nYou share on-call for production protocols with the engineer who wrote the module. Rotations are written down. We do not page you for a marketing-site outage. Kubernetes is useful; chain-specific ops is the job.",
    [
      "Run CI for contracts and dApps, including fork tests and preview deploys.",
      "Operate RPCs, indexers, bots, and relayers.",
      "Instrument logs, traces, and on-chain alerts (failed keepers, stalled subgraphs, unusual admin txs).",
      "Secure secrets and signer infrastructure; no keys in chat.",
      "Run deploy playbooks: hardware wallet or multisig, dry run, then mainnet.",
      "Write the runbook the next person on-call actually follows.",
      "Keep staging and prod from drifting without a PR.",
    ],
    [
      "Production DevOps or SRE.",
      "At least one chain’s node, RPC, or indexer stack you have operated when it was broken.",
      "Comfortable with GitHub Actions (or similar) and Linux.",
    ],
    ["Foundry CI", "Tenderly or Defender", "SOC2", "Kubernetes you did not only tutorial"],
  ),
  role(
    "qa-engineer-web3",
    "QA Engineer, Web3",
    "Engineering",
    "Mid",
    "E2E · forks · wallets",
    "Break wallet flows, mints, and DeFi paths before users do — browsers, chains, and connectors.",
    "Web3 QA is not clicking a form. You test forks, failed txs, the ugly middle of every journey, and at least two wallets. You write bugs with transaction hashes and traces, not “it didn’t work.”\n\nYou gate releases with a checklist engineering respects. You are not a human test script for work that should be automated; you automate the stable paths and explore the rest. BrickFi invest/withdraw and client mint/admin are the first suites.",
    [
      "Write E2E coverage for dApps and admin tools (Playwright or equivalent).",
      "Maintain fixtures, Anvil forks, and test wallets.",
      "Log bugs with tx hashes, network, wallet, and reproduction steps.",
      "Gate releases with a checklist that includes wrong network, reject, and indexer lag.",
      "Pair with frontend and contracts when a failure is ambiguous.",
      "Track flaky tests; do not let CI become theater.",
      "Regression-test after contract upgrades and ABI changes.",
    ],
    [
      "2+ years QA or SDET including crypto or fintech.",
      "You have automated browser tests, not only written manual scripts.",
      "Comfortable reading a block explorer and a failed receipt.",
    ],
    ["Foundry", "Mobile wallets", "Load testing", "Accessibility testing"],
  ),
  role(
    "engineering-manager",
    "Engineering Manager",
    "Engineering",
    "Lead",
    "People · delivery · Web3",
    "Manage a pod of Web3 engineers — performance, staffing, and shipping — without becoming the bottleneck on every diff.",
    "You have been a strong IC. Now you make a team of ICs better. You still read a diff. You run 1:1s, leveling, and hiring for your pod. Delivery health is shared with the delivery lead.\n\nA typical pod is 4–7 people across contracts, frontend, and maybe ops. You protect focus through audits and launches. You do not take every on-call page; you make sure coverage exists.",
    [
      "Run 1:1s, leveling, and hiring for your pod.",
      "Own delivery health with the delivery lead (dates, load, quality).",
      "Protect focus and quality through audits and launches.",
      "Coach mid through senior engineers; you still review the risky PRs.",
      "Escalate scope and client issues to the Director/VP/CTO before they blow up.",
      "Write performance reviews that are specific, not adjective soup.",
      "Keep the pod’s on-call and launch checklist current.",
    ],
    [
      "Managed engineers, or been a tech lead ready to manage (say so clearly in the application).",
      "Web3 delivery experience — you know what an audit week does to a plan.",
      "You can still read Solidity or TypeScript well enough to coach, not only schedule.",
    ],
    ["Studio teams", "Multi-timezone", "Hiring you can point to"],
  ),
  role(
    "director-of-engineering",
    "Director of Engineering",
    "Engineering",
    "Lead",
    "Multi-team · clients · quality",
    "Run several engineering teams — protocol, product, and infra — and the quality bar the CTO sets.",
    "You translate studio strategy into staffing, roadmaps, and postmortems. VP of Engineering and the CTO are your partners. You hire and develop managers and staff ICs. You are accountable for client technical outcomes, not only internal happiness.\n\nBrickFi and the client bench both sit in your world. You standardize reviews, incident process, and launch gates so every pod is not inventing them.",
    [
      "Own the engineering roadmap across products including BrickFi.",
      "Hire and develop managers and staff ICs.",
      "Standardize reviews, incident process, and launch gates.",
      "Be accountable for client technical outcomes and escalations.",
      "Balance BrickFi investment against client capacity in writing, not in Slack lore.",
      "Partner with Head of Security on audit calendars.",
      "Represent engineering in sales-to-delivery handoffs when the work is large.",
    ],
    [
      "Directed or built engineering orgs in software, ideally crypto.",
      "You have managed managers, not only ICs.",
      "Evidence of a launch or incident process you installed that people actually used.",
    ],
    ["Agency or studio", "Security-minded", "Multi-product portfolio"],
  ),
  role(
    "vp-of-engineering",
    "VP of Engineering",
    "Engineering",
    "Executive",
    "Org · mainnet · P&L-aware",
    "Second seat under the CTO: the engineering org, the delivery machine, and the technical hiring brand.",
    "You scale Lootrushs from a studio bench to a durable engineering company. You still know what a proxy is. You own delivery capacity and technical risk for the company. You partner with Head of Design, Product, and Growth.\n\nYou stand in for the CTO with clients and candidates. You do not disappear into vendor meetings. You build the org from mid to staff and make sure we can say no to work we cannot staff.",
    [
      "Build the engineering org from mid to staff, including managers.",
      "Own delivery capacity and technical risk for BrickFi and the client bench.",
      "Partner with Head of Design, Product, and Growth on what we sell and hire.",
      "Stand in for the CTO with clients and senior candidates.",
      "Own the hiring brand for engineering: loops, bars, and comp bands with the recruiter.",
      "Install and keep launch/incident standards across pods.",
      "Give the CTO a written view of risk, not a surprise the week of mainnet.",
    ],
    [
      "VP or Head of Engineering experience, or equivalent org-building in crypto or software.",
      "You have owned a multi-team delivery number and a quality bar at the same time.",
      "You can still review a serious technical design.",
    ],
    ["Founding VP", "Multi-product studio", "Services plus product P&L awareness"],
  ),
  role(
    "smart-contract-security-engineer",
    "Smart Contract Security Engineer",
    "Security",
    "Senior",
    "Audits · fuzzing · invariants",
    "Threat-model, review, and harden the contracts Lootrushs ships — before mainnet, not after an incident.",
    "You sit with protocol engineers, write invariants, and catch what late audits miss. We still use external auditors on larger launches. This seat is the person inside Lootrushs who can block a deploy.\n\nYou will not run corporate IT or SOC2 as your main job. You will sit with protocol engineers while they can still change the design. Expert-level familiarity with EVM exploit classes is required; a PDF-only background is not enough.",
    [
      "Review contracts, upgrade paths, and admin powers before they are marked done.",
      "Run fuzzing, invariant, and differential tests on critical paths.",
      "Write findings engineers can fix: severity, test, and a suggested patch when you can.",
      "Define launch checklists and incident playbooks with Ops.",
      "Join external audit kickoffs with a packet that is not a surprise to us.",
      "Threat-model BrickFi issuance and client vaults specifically, not only “generic DeFi.”",
      "Track residual risk after an audit and make sure it is visible to the CTO.",
    ],
    [
      "Prior audit, bounty, or protocol security work — with examples you can discuss.",
      "Expert knowledge of Solidity exploit classes.",
      "You can write Foundry tests, not only PDF reports.",
    ],
    ["Echidna / Medusa", "Formal methods", "Public writeups", "RWA or permissioned tokens"],
  ),
  role(
    "head-of-security",
    "Head of Security",
    "Security",
    "Executive",
    "Program · audits · keys",
    "Own security for the studio: reviews, keys, vendors, and how we talk about risk with clients.",
    "You build the security function from this senior IC (and future hires) to a program. You report to the CTO. You set review and key-management policy. You coordinate external audits. You brief leadership and clients on residual risk without theatre or false comfort.\n\nYou will hire. You will still read a serious contract when the bench is thin. You will not turn this into a GRC-only job while mainnet is unprotected.",
    [
      "Set review and key-management policy (who can deploy, how we store seeds, multisig rules).",
      "Hire and develop the security team.",
      "Coordinate external audits and make sure the packet is complete.",
      "Brief leadership and clients on residual risk in writing.",
      "Own incident command for security events (key leak, suspected exploit, vendor breach).",
      "Decide when we refuse work on security grounds.",
      "Partner with Legal on what we can say publicly after a launch.",
    ],
    [
      "Led security or been a principal auditor ready to lead a function.",
      "You have been in the room for a real incident or a high-stakes audit.",
      "You can talk to engineers and to a founder without two different personalities.",
    ],
    ["Incident command", "Compliance / SOC2", "Client-facing security reviews"],
  ),
  role(
    "web3-data-engineer",
    "Web3 Data / Indexer Engineer",
    "Data",
    "Mid",
    "The Graph · Ponder · SQL",
    "Turn events into product data: subgraphs, indexers, and pipelines that BrickFi reporting and client UIs can trust.",
    "dApps die when the indexer lies. You own events-to-APIs, including reorgs and backfills. Current mix is subgraphs, a TypeScript indexer (Ponder or equivalent), and Postgres for BrickFi reporting.\n\nIf we are behind, you publish a status — you do not let the dashboard pretend. You work with protocol and frontend so a contract change does not silently break reporting.",
    [
      "Build subgraphs, Ponder/Envio indexers, or custom consumers for BrickFi and client contracts.",
      "Model vaults, NFTs, and RWA positions so the app does not scrape RPC in the browser.",
      "Handle backfill, reorgs, and lag; publish when we are behind.",
      "Expose APIs or SQL views for product and ops reports.",
      "Add fixtures so a contract change does not silently break reporting.",
      "Partner with protocol engineers on event design before they deploy.",
      "Keep a simple data dictionary so PMs and support are not guessing column names.",
    ],
    [
      "Shipped an indexer or subgraph.",
      "TypeScript or Rust plus SQL you can tune.",
      "You understand why a reorg can double-count and how you prevent that.",
    ],
    ["Dune", "ClickHouse", "Kafka", "Worked next to a protocol team"],
  ),
  role(
    "product-manager-web3",
    "Product Manager, Web3",
    "Product",
    "Mid",
    "Protocols · UX · delivery",
    "Turn chain constraints into a shippable product — scope, sequencing, and honest client calls.",
    "You sit between founders, engineers, and designers. You know when something must be on-chain. You write specs that include threat models and empty states. You sequence MVPs that can actually deploy.\n\nYou own a product surface end to end (BrickFi or a client). If you have only written user stories for a CRUD app, this will be a bad fit. Overlap a few hours with US Eastern.",
    [
      "Write specs that include user flow, on-chain vs off-chain, empty/error/admin, and threat notes.",
      "Sequence MVPs with testnet, audit window, and mainnet on the calendar.",
      "Run client communication without hiding risk.",
      "Sit in engineering planning; cut scope instead of stretching the date in silence.",
      "Define a few success metrics after launch. TVL is not always the right one.",
      "Triage inbound feature requests against the ship list.",
      "Keep a written decision log so we do not relitigate allowlists every week.",
    ],
    [
      "3+ years PM with a shipped crypto or fintech product.",
      "You can talk to engineers about wallets and contracts without bluffing.",
      "Writing a founder can forward internally.",
    ],
    ["RWA", "Token launches", "B2B or client services", "SQL or basic on-chain analytics"],
  ),
  role(
    "senior-product-manager-web3",
    "Senior Product Manager, Web3",
    "Product",
    "Senior",
    "Multi-stream · RWA · protocol",
    "Lead product on BrickFi or a protocol family. Mentor mid PMs. Push back on scope that cannot ship.",
    "Senior PM means you have launched, missed, and launched again. You can hold a room with the CTO. You own the roadmap for a major product. You negotiate scope with clients and engineering.\n\nYou mentor associate and mid PMs when we have them. You define success with data, not vibes. BrickFi or a multi-contract client is the usual seat.",
    [
      "Own roadmap for a major product (BrickFi or a protocol family).",
      "Mentor associate and mid PMs.",
      "Negotiate scope with clients and engineering in writing.",
      "Define success metrics with data and look at them after launch.",
      "Run the hardest workshops (what is on-chain, what waits, what we refuse).",
      "Partner with Legal on eligibility and disclosures when the product is RWA.",
      "Represent product in launch and incident reviews.",
    ],
    [
      "5+ years PM, senior ownership of a live product.",
      "At least one crypto, marketplace, or high-trust financial product you can discuss in detail.",
      "Evidence you have said no to a stakeholder and been right.",
    ],
    ["Marketplace", "RWA", "Developer products", "Managed another PM"],
  ),
  role(
    "tokenomics-researcher",
    "Tokenomics Researcher",
    "Product",
    "Senior",
    "Incentives · modeling · governance",
    "Design incentive systems that survive users — emissions, utility, and governance that are not only a spreadsheet.",
    "Clients ask for a token. You tell them whether they need one, then model it if they do. This is a contract seat because the work is bursty around launches.\n\nYou stress-test governance and attacker incentives. You write memos engineers and lawyers can use. You support launch parameters and later tuning. You will not rubber-stamp a “number go up” emissions curve.",
    [
      "Model supply, emissions, utility, and unlocks with assumptions written down.",
      "Stress-test governance and attacker incentives.",
      "Write memos engineers and lawyers can use, not only a pretty chart.",
      "Support launch parameters and post-launch tuning.",
      "Say no, in writing, when a token does not serve the product.",
      "Work with the PM and contract engineer so parameters match the code.",
    ],
    [
      "Prior token or protocol incentive design that shipped.",
      "You can defend a model to a skeptical engineer and a counsel.",
      "Comfortable with uncertainty; you do not present point estimates as facts.",
    ],
    ["cadCAD or similar", "Mechanism design background", "DAO operations", "Published research"],
    "Contract",
  ),
  role(
    "head-of-product",
    "Head of Product",
    "Product",
    "Executive",
    "Portfolio · BrickFi · clients",
    "Own the product org and the studio’s product bets — from APM to senior PM — beside the CTO.",
    "You decide what we build, in what order, and what we refuse. Design and engineering are your peers. You set product strategy for Lootrushs and BrickFi. You hire and level the PM team. You align clients with a portfolio the bench can ship.\n\nYou sit on leadership with the CTO, Head of Design, and VP of Engineering. You will still write a spec when the team is thin.",
    [
      "Set product strategy for Lootrushs and BrickFi.",
      "Hire and level the PM team.",
      "Align clients with a portfolio the bench can actually staff.",
      "Sit on leadership with CTO, Head of Design, and VP Eng.",
      "Own the no-list: work we will not take.",
      "Install product rituals (specs, reviews, metrics) people use.",
      "Be accountable for BrickFi’s product outcomes, not only process.",
    ],
    [
      "Head or Director of Product, or founding PM who scaled.",
      "Crypto or similarly technical product background.",
      "You have hired PMs and killed a roadmap item in the same quarter.",
    ],
    ["RWA", "Multi-sided markets", "Studio plus owned product"],
  ),
  role(
    "web3-community-manager",
    "Web3 Community Manager",
    "Growth",
    "Mid",
    "Discord · X · Telegram",
    "Run the rooms where users and candidates live — without turning them into spam.",
    "Lootrushs needs a public face technical enough to be trusted. BrickFi’s community is part of this seat: investors and curious users, not only degens. You own Discord/Telegram ops, mods, and incident comms. You write updates for launches and hiring.\n\nYou surface feedback to product and engineering. You make Lootrushs visible to Web3 talent. You will not be asked to fake engagement with bots.",
    [
      "Own Discord, Telegram, and X ops, including mods and incident comms.",
      "Write updates for launches, incidents, and hiring that engineering will stand behind.",
      "Surface user and candidate feedback to product and engineering weekly.",
      "Make Lootrushs visible to Web3 talent without sounding like a shill account.",
      "Set rules and enforce them; document bans.",
      "Coordinate AMAs only when we have something real to say.",
      "Keep a simple calendar so we are not silent for six weeks then loud for one.",
    ],
    [
      "2+ years community in crypto, gaming, or developer tools.",
      "Writing samples. We will read them.",
      "You have handled a messy thread or incident without making it worse.",
    ],
    ["AMAs", "Ambassador programs", "BrickFi or RWA communities", "Light design or video"],
  ),
  role(
    "web3-developer-relations",
    "Developer Relations, Web3",
    "Growth",
    "Mid",
    "Docs · SDKs · talks",
    "Make Lootrushs SDKs and docs easy to adopt — and show up where Web3 engineers already are.",
    "You turn internal engineering into public signal: docs, examples, talks, and answers that hire and sell. You have shipped code and you can teach it.\n\nYou support integrators on wallets, contracts, and APIs. You feed product gaps back to engineering. You will not be a booth-only mascot; you will write and, when needed, open a PR.",
    [
      "Write developer docs and sample apps for the surfaces we want adopted.",
      "Support integrators on wallets, contracts, and APIs.",
      "Speak at meetups and Spaces when we have something specific to show.",
      "Feed product gaps back to engineering in writing.",
      "Keep examples running against current ABIs and networks.",
      "Help hiring by being a credible public engineer for Lootrushs.",
      "Triage GitHub issues and Discord technical questions with the team.",
    ],
    [
      "You have shipped production code and you can teach it.",
      "Public writing or talks we can watch or read.",
      "Comfortable in TypeScript and at least reading Solidity.",
    ],
    ["OSS maintainership", "Workshops", "SDK design", "Prior DevRel at a protocol"],
  ),
  role(
    "business-development-web3",
    "Business Development, Web3",
    "Growth",
    "Mid",
    "Partnerships · protocols · studios",
    "Bring in protocol, studio, and RWA work — from first conversation to a scoped statement of work we can staff.",
    "You hunt and close engagements that match what we build: contracts, dApps, DeFi, and real-estate platforms. hello@lootrushs.com is already a mailbox. You reply, qualify, and write the SOW with an engineer on the second call.\n\nComp is base plus commission on signed work, spelled out in the offer. We will not pay you to promise a token launch we cannot legally or technically do.",
    [
      "Source and qualify Web3 clients: chain, existing code, date, budget.",
      "Run discovery with an engineer in the room once the brief is real.",
      "Negotiate SOWs without promising vapor.",
      "Keep pipeline matched to capacity (who is free, what we refuse).",
      "Respond to inbound within two business days.",
      "Hand closed work to the delivery lead cleanly.",
      "Maintain a simple tracker; no 40-field CRM on day one.",
    ],
    [
      "2+ years BD or sales in crypto, fintech, or software services — with deals you can name.",
      "You can sit in a technical meeting without interrupting to close.",
      "Writing a founder can forward to their counsel.",
    ],
    ["RWA network", "Studio bizdev", "NDAs and slow legal", "Existing protocol relationships"],
  ),
  role(
    "technical-writer-web3",
    "Technical Writer, Web3",
    "Growth",
    "Mid",
    "Docs · specs · explainers",
    "Write the documents that let engineers, users, and auditors understand what we shipped.",
    "Whitepapers, READMEs, launch posts, and BrickFi help text — if it has to be true and readable, it is this job. Contract seat because the load spikes around launches and audits.\n\nYou turn design docs into public docs. You write integration guides and runbooks. You edit engineering prose without flattening it. You keep terminology consistent. You will not be asked to write hype threads as your main job.",
    [
      "Turn internal design docs into public docs and help center articles.",
      "Write integration guides and runbooks for BrickFi and client launches.",
      "Edit engineering prose without flattening the meaning.",
      "Keep terminology consistent across site, docs, and product copy.",
      "Sit with engineers and replay what you understood until it matches the code.",
      "Prepare audit and partner packets that are complete.",
    ],
    [
      "A portfolio of technical writing, ideally crypto or developer tools.",
      "You can read a spec or a Solidity interface well enough to ask the right questions.",
      "Native or near-native English writing.",
    ],
    ["MDX", "Diagrams", "Prior protocol docs", "Journalism or research background"],
    "Contract",
  ),
  role(
    "growth-marketing-web3",
    "Growth Marketing, Web3",
    "Growth",
    "Mid",
    "Content · SEO · campaigns",
    "Get Lootrushs in front of founders who need a studio and candidates who want to build here.",
    "Hiring and pipeline both depend on being findable. You own site content, campaigns, and the BrickFi story. You measure what produces leads and applicants. You partner with design and DevRel.\n\nYou will not run fake engagement. You will write about technical products in a way a founder can forward. SEO for lootrushs.com and campaigns for launches and hiring are the core.",
    [
      "Plan content and SEO for lootrushs.com.",
      "Run campaigns for launches and hiring.",
      "Measure what produces leads and applicants; kill what does not.",
      "Partner with design and DevRel on assets and technical accuracy.",
      "Write or edit pages that match what we actually ship.",
      "Keep a simple calendar and a source of truth for claims.",
      "Work with Community so social and site are not two different companies.",
    ],
    [
      "2+ years growth or content marketing.",
      "Comfort writing about technical products.",
      "Examples of work you can attribute (site, campaign, newsletter).",
    ],
    ["Crypto audience", "Paid social", "SEO you can explain", "Analytics setup"],
  ),
  role(
    "head-of-growth",
    "Head of Growth",
    "Growth",
    "Executive",
    "Brand · pipeline · hiring",
    "Own growth, community, DevRel, and BD as one function — the top of the growth ladder.",
    "You sit with the CTO. Your job is inbound work and inbound talent, without cheapening the brand. You hire community, marketing, DevRel, and BD. You own funnel metrics for clients and candidates.\n\nYou protect voice and technical honesty. You will fire a channel that makes us look like a mint-spam shop. You will still write or edit a page when the team is thin.",
    [
      "Set growth strategy for the studio and BrickFi.",
      "Hire community, marketing, DevRel, and BD.",
      "Own funnel metrics for clients and candidates.",
      "Protect voice and technical honesty across channels.",
      "Partner with Product and Engineering on what we can claim.",
      "Decide spend; no vanity dashboards.",
      "Represent Lootrushs with press and partners when needed.",
    ],
    [
      "Led growth or marketing in crypto or developer-led companies.",
      "You have owned a pipeline number and a brand at the same time.",
      "Evidence you have hired marketers or community people.",
    ],
    ["Founding marketer", "Community-led growth", "Studio or services growth"],
  ),
  role(
    "web3-recruiter",
    "Web3 Recruiter / Talent",
    "Operations",
    "Mid",
    "Sourcing · designer-to-CTO",
    "Fill the board you are looking at: source, screen, and close Web3 talent across every open role.",
    "You already know where Solidity engineers and crypto designers hang out. You own the careers funnel on lootrushs.com: sourcing, screening, loops, and a candidate experience that matches the brand.\n\nYou partner with hiring managers on bars. You report pipeline health weekly. You will not spray InMails that read like a bot. You will read a resume and a GitHub before you book a founder’s time.",
    [
      "Source and screen across every open role on this board.",
      "Run a candidate experience that matches the brand (clear process, no ghosting).",
      "Partner with hiring managers on bars and scorecards.",
      "Report pipeline health weekly: pass-through, time-to-offer, drop-off.",
      "Write honest outreach; no fake “loved your Uniswap fork.”",
      "Close offers with the hiring manager; know our bands.",
      "Keep the ATS (or spreadsheet) current so we do not lose people.",
    ],
    [
      "Recruited technical or crypto talent before.",
      "You can talk about Solidity, design, and product roles without bluffing.",
      "References or a track record of closes, not only sourced profiles.",
    ],
    ["In-house startup", "Agency desk", "International hiring", "Employer-brand work"],
  ),
  role(
    "web3-delivery-lead",
    "Delivery Lead / Project Manager",
    "Operations",
    "Mid",
    "Scrum · mainnet · clients",
    "Keep multi-stream Web3 builds on time — contracts, indexers, and UI — without fake-agile theater.",
    "You understand audits, testnets, and why staging is not shipped. You run one or two engagements at a time: a board engineering respects, status the client can forward, and a launch checklist that matches how we deploy.\n\nYou do not manage people. You do manage dates and dependencies. Linear (or equivalent) is fine. We will not make you run Jira theater.",
    [
      "Plan work across protocol, frontend, and infra with the engineers doing it.",
      "Track audits, keys, freeze dates, and launch windows.",
      "Run truthful client status — yellow items stay yellow.",
      "Unblock engineers: missing designs, missing RPC, missing client feedback.",
      "After launch, file the retro and the runbook link in the same place.",
      "Keep BrickFi and client calendars from colliding without a conversation.",
      "Escalate to the EM or CTO before a date slips in silence.",
    ],
    [
      "3+ years delivery, technical PM, or producer work.",
      "A crypto, payments, or high-compliance launch — not only a content site.",
      "Comfortable in Linear or equivalent.",
    ],
    ["Studio or agency", "US–EU overlap", "Audit coordination"],
  ),
  role(
    "legal-compliance-web3",
    "Legal & Compliance, Web3",
    "Operations",
    "Senior",
    "RWA · tokens · TOS",
    "Keep BrickFi and client launches inside the lines — tokens, RWA, privacy, and contractor paper.",
    "You are counsel or a compliance lead who can talk to engineers. You do not block shipping for sport; you shape it. Contract seat because we use external firms for some jurisdictions and need a dedicated owner inside.\n\nYou review token, RWA, and product flows for legal risk. You own policies, TOS, and privacy updates. You coordinate external counsel. You educate the studio on what we will not ship.",
    [
      "Review token, RWA, and product flows for legal risk before they are built as if they were allowed.",
      "Own policies, terms, and privacy updates on lootrushs.com and BrickFi.",
      "Coordinate external counsel and keep a matter list.",
      "Educate the studio on what we will not ship, in writing.",
      "Review contractor and client paper with the CTO or ops.",
      "Partner with product on eligibility, disclosures, and marketing claims.",
      "Be available for launch week questions without becoming a bottleneck on copy tweaks.",
    ],
    [
      "Legal, compliance, or policy work in crypto or fintech.",
      "You can read a product spec and spot the securities or privacy issue.",
      "Comfortable working with engineers who will ask “can we ship Friday?”",
    ],
    ["Bar admission", "Securities", "International", "In-house at a protocol or fintech"],
    "Contract",
  ),
  role(
    "token-operations-finance",
    "Finance / Token Operations",
    "Operations",
    "Mid",
    "Treasury · payroll · reporting",
    "Run studio finance plus on-chain treasury ops — payroll, invoices, and token movements with two-person control.",
    "Crypto companies die on ops. You keep books and wallets boring and correct. You own bookkeeping, invoices, and contractor payments. You operate treasury checklists with engineering. You report burn and project margins.\n\nYou support BrickFi financial reporting with data. Two-person control on chain movements is not optional. You will not be asked to be a full CFO on day one; you will be asked to not lose the plot on wallets and invoices.",
    [
      "Own bookkeeping, invoices, and contractor payments.",
      "Operate treasury checklists with engineering (two-person control, recorded txs).",
      "Report burn and project margins monthly.",
      "Support BrickFi financial reporting with the data engineer and PM.",
      "Keep a clean list of wallets, signers, and what each is for.",
      "Work with the recruiter and leads on offer comp math.",
      "Flag when a client is late or a project is underwater.",
    ],
    [
      "Finance operations experience (startup, studio, or similar).",
      "Comfort with wallets and basic on-chain transfers.",
      "Spreadsheet and bookkeeping hygiene; we will look at a sample if you have one.",
    ],
    ["Crypto payroll", "RWA reporting", "QuickBooks or similar", "US and international contractors"],
  ),
  role(
    "cto",
    "Chief Technology Officer",
    "Leadership",
    "Executive",
    "Vision · protocol · org",
    "The top of the ladder: technical vision, the engineering/design/product bar, and every mainnet we put our name on.",
    "Lootrushs is a Web3 development company. BrickFi is our product; the rest is client protocol and dApp work. The CTO owns how we build — from a designer pairing on a flow to protocol architecture — and hires the leaders under this role (VP of Engineering, Head of Design, Head of Product, Head of Security).\n\nYou will still read diffs. You will be on the call where a client asks for an unaudited upgrade next Friday. You will refuse work we cannot staff or cannot secure. Remote, US Eastern overlap. Base $280k–$360k plus token or equity. This is not a conference-only seat.",
    [
      "Set technical strategy across EVM, Solana, BrickFi, and client work.",
      "Hire and develop the leadership bench from design through engineering.",
      "Be accountable for architecture, security posture, and launch quality.",
      "Represent Lootrushs with clients, partners, and senior candidates.",
      "Keep the studio shipping: short written plans, not slideware.",
      "Scope and sometimes refuse work.",
      "Stay on-call for production incidents until Ops coverage exists.",
      "Set defaults: languages, review bar, keys, which chains we take.",
    ],
    [
      "You have been CTO, founding engineer, or VP Eng at a shipped crypto or deep-technical product.",
      "You can still read a contract and a Figma file.",
      "Evidence you have built teams, not only systems.",
      "Willing to be in the details on BrickFi and on client mainnets.",
    ],
    ["RWA / real estate tech", "Studio or multi-product org", "Public technical presence", "Services plus product"],
  ),
];

export const departments: Department[] = [
  "Design",
  "Engineering",
  "Security",
  "Data",
  "Product",
  "Growth",
  "Operations",
  "Leadership",
];

export const levels: Level[] = ["Mid", "Senior", "Staff", "Lead", "Executive"];

export function getJob(slug: string) {
  return jobs.find((job) => job.slug === slug);
}

export const careersEmail = `careers@${site.domain.replace("www.", "")}`;
